version: '3.8'
services:
  db:
    image: mysql:8.0  # Puedes cambiar a postgres si lo prefieres
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: sitios_turisticos_aburra
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/sitios_turisticos.sql:/docker-entrypoint-initdb.d/sitios_turisticos.sql
    ports:
      - "3307:3306"
  
  web:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: sitios_turisticos_aburra
