version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: TouristDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/places.sql:/docker-entrypoint-initdb.d/places.sql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: TouristDB
      JWT_SECRET: tu_clave_secreta_muy_segura
    volumes:
      - ./server/public:/app/public
      - ./server/app.js:/app/app.js
      - /app/node_modules