version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: sitios_turisticos_aburra
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/sitios_turisticos.sql:/docker-entrypoint-initdb.d/sitios_turisticos.sql
    ports:
      - "3307:3306"  # Cambié a 3307 en el host para evitar conflictos
  web:
    build: ./server
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: sitios_turisticos_aburra
    volumes:
      - ./public:/usr/src/app/public  # Monta la carpeta pública para servir los archivos estáticos
