version: '3.8'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: TouristDB  # Cambiado a TouristDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./database/places.sql:/docker-entrypoint-initdb.d/places.sql  # Cambiado a places.sql
    ports:
<<<<<<< HEAD
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

=======
      - "3307:3306"  # Cambié a 3307 en el host para evitar conflictos
>>>>>>> 1bb3beacb28d1c71e98f2d3e5c41a47023a27d65
  web:
    build: ./server  # Construye el Dockerfile ubicado en la carpeta server
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
<<<<<<< HEAD
      DB_NAME: TouristDB  # Cambiado a TouristDB
    volumes:
      - ./public:/app/public  # Monta la carpeta 'public' para servir los archivos estáticos
=======
      DB_NAME: sitios_turisticos_aburra
    volumes:
      - ./public:/usr/src/app/public  # Monta la carpeta pública para servir los archivos estáticos
>>>>>>> 1bb3beacb28d1c71e98f2d3e5c41a47023a27d65
